apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "only-kube-apiserver"
spec:
  description: "این پاد فقط اجازهٔ DNS و صحبت با kube-apiserver را دارد"
  endpointSelector:
    matchLabels:
      run: entity-test
  egress:
  - toEndpoints:
    - matchLabels:
        "k8s:io.kubernetes.pod.namespace": kube-system
        k8s-app: kube-dns
    toPorts:
    - ports:
      - port: "53"
        protocol: ANY
      rules:
        dns:
        - matchPattern: "*"
  - toEntities:
    - kube-apiserver

#kubectl exec entity-test -- curl -sk --max-time 5 -o /dev/null -w "kube-apiserver -> HTTP:%{http_code}\n" https://kubernetes.default.svc
#kube-apiserver -> HTTP:403 # (همچنان وصل می‌شود)
#kubectl exec entity-test -- curl -s --max-time 5 -o /dev/null -w "example.com    -> HTTP:%{http_code}\n" https://example.com
#example.com    -> HTTP:000
#command terminated with exit code 28
