apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "restrict-egress-to-example-com"
spec:
  description: "فقط اجازهٔ خروج به example.com، بقیهٔ دنیا بسته"
  endpointSelector:
    matchLabels:
      run: fqdn-test
  egress:
  - toEndpoints:
    - matchLabels:
        "k8s:io.kubernetes.pod.namespace": kube-system
        k8s-app: kube-dns
    toPorts:
    - ports:
      - port: "53"
        protocol: ANY
      rules:
        dns:
        - matchPattern: "*"
  - toFQDNs:
    - matchName: "example.com"
    toPorts:
    - ports:
      - port: "443"
        protocol: TCP
      - port: "80"
        protocol: TCP
        
#root@master:~# kubectl exec fqdn-test -- curl -s --max-time 5 -o /dev/null -w "example.com -> HTTP:%{http_code}\n" https://example.com
#example.com -> HTTP:200
#root@master:~# kubectl exec fqdn-test -- curl -s --max-time 5 -o /dev/null -w "github.com  -> HTTP:%{http_code}\n" https://github.com
#github.com  -> HTTP:000
#command terminated with exit code 28
