apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: s3-store
spec:
  configuration:
    destinationPath: s3://backups/
    endpointURL: http://object-store:9000   # omit for AWS S3
    s3Credentials:
      accessKeyId:
        name: object-store
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: object-store
        key: ACCESS_SECRET_KEY
    wal:
      compression: gzip
